# Generated by Django 2.2.1 on 2019-09-23 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quentity',
            new_name='quantity',
        ),
    ]
