# Generated by Django 2.2.1 on 2019-10-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20191002_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliveryCharge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
