# Generated by Django 2.2.1 on 2019-10-03 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20191002_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='calceledDate',
            new_name='canceledDate',
        ),
    ]
