# Generated by Django 2.2.1 on 2019-10-15 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20191003_0855'),
        ('order', '0005_auto_20190928_1627'),
    ]

    operations = [
    ]
