# Generated by Django 2.2.1 on 2019-11-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_merge_20191015_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cod',
            field=models.BooleanField(default=True),
        ),
    ]
