# Generated by Django 2.2.1 on 2019-11-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_cod'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_successful',
            field=models.BooleanField(default=False),
        ),
    ]
