# Generated by Django 2.2.1 on 2019-11-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_order_successful'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shippingAddress1',
            new_name='shippingFullName',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shippingPostcode',
            new_name='shippingPinCode',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shippingName',
            new_name='shippingState',
        ),
        migrations.AddField(
            model_name='order',
            name='shippingMobileNumber',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='shippingStreetAddress',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='order',
            name='shippinglandmark',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
