# Generated by Django 2.2.1 on 2019-11-24 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20190526_0911'),
        ('order', '0011_auto_20191124_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_object',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.CharField(max_length=250),
        ),
    ]
