# Generated by Django 2.2.1 on 2019-12-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_order_dispatched'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='txn_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='txn_id',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
