# Generated by Django 2.2.1 on 2019-12-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20191209_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='txn_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
