# Generated by Django 2.2.1 on 2019-12-10 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_order_txn_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
    ]
