# Generated by Django 2.2.1 on 2019-12-10 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_remove_orderitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
    ]
