# Generated by Django 2.2 on 2021-06-01 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tocken', models.CharField(blank=True, max_length=250)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='GBP Order Total')),
                ('deliveryCharge', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('emailAddress', models.EmailField(blank=True, max_length=250, verbose_name='Email Address')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('billingName', models.CharField(blank=True, max_length=250)),
                ('billingAddress1', models.CharField(blank=True, max_length=250)),
                ('billingCity', models.CharField(blank=True, max_length=250)),
                ('billingPostcode', models.CharField(blank=True, max_length=10)),
                ('billingCountry', models.CharField(blank=True, max_length=200)),
                ('shippingFullName', models.CharField(blank=True, max_length=250)),
                ('shippingMobileNumber', models.CharField(blank=True, max_length=15)),
                ('shippingPinCode', models.CharField(blank=True, max_length=10)),
                ('shippingStreetAddress', models.CharField(blank=True, max_length=250)),
                ('shippinglandmark', models.CharField(blank=True, max_length=250)),
                ('shippingCity', models.CharField(blank=True, max_length=250)),
                ('shippingState', models.CharField(blank=True, max_length=250)),
                ('shippingCountry', models.CharField(blank=True, max_length=200)),
                ('delivered', models.BooleanField(default=False)),
                ('deliveredDate', models.DateTimeField(blank=True, null=True)),
                ('canceled', models.BooleanField(default=False)),
                ('canceledDate', models.DateTimeField(blank=True, null=True)),
                ('cod', models.BooleanField(default=True)),
                ('order_successful', models.BooleanField(default=False)),
                ('dispatched', models.BooleanField(default=False)),
                ('txn_id', models.CharField(blank=True, max_length=250)),
                ('txn_date', models.DateTimeField(blank=True, null=True)),
                ('txn_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Order',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='GBP Price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
            options={
                'db_table': 'OrderItem',
            },
        ),
    ]
